name: Build custom

on: [workflow_dispatch]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Initialize environment
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt update 
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget
      
    - name: Update feeds
      run: cd $GITHUB_WORKSPACE && ./scripts/feeds update -a
      
    - name: Install feeds
      run: cd $GITHUB_WORKSPACE && ./scripts/feeds install -a

    - name: Install sdk
      run: |
        cd $GITHUB_WORKSPACE
        wget https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9/config.buildinfo -O .config
        wget https://github.com/trinidude4/openwrt/releases/download/sdk-latest/sdk.tar.xz
        tar -xhf sdk.tar.xz
        ./scripts/ext-toolchain.sh \
            --toolchain staging_dir/toolchain-arm_cortex-a9+vfpv3-d16_gcc-12.2.0_musl_eabi \
            --overwrite-config \
            --config mvebu/cortexa9
        ./scripts/ext-tools.sh --refresh

    - name: Make defconfig
      run: |
        cd $GITHUB_WORKSPACE
        make defconfig
        
    - name: Build Image
      run: |
        cd $GITHUB_WORKSPACE
        make package/kernel/mwlwifi/compile V=s
    - name: Upload directories
      uses: actions/upload-artifact@main
      with:
        name: build_upload
        path: |
          bin

    - name: Upload files
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: mwlwifi-latest
        prerelease: false
        title: Latest mwlwifi
        files: |
          bin/targets/mvebu/cortexa9/packages/kmod-mwlwifi_*.ipk
          bin/targets/mvebu/cortexa9/packages/mwlwifi-firmware-*.ipk
